# This is a basic workflow to help you get started with Actions

name: Create Archive

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: pull latest and remove old file from repo
        run: |
          git config --global user.name "Endobear"
          git config --global user.email "enriquemessias.souza@gmail.com"
          git config pull.rebase false
          git pull
          rm -f PixelmonMusicPack.zip
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'PixelmonMusicPack.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          
      - name: push changes to remote
        run: |
          git add -A
          git commit -m "new pack"
          git push --force
